services:
  gpawindev:
    build:
      context: windows-dockerfiles
      dockerfile: Dockerfile
      args:
        RUST_VERSION: 1.81.0
    platform: windows/amd64
    volumes:
      - ./:C:\Users\ContainerAdministrator\GuestProxyAgent:rw
    working_dir: C:\Users\ContainerAdministrator\GuestProxyAgent
