# Generated by rust2rpm 27 and manual updated for deamon service install and local build
#  rust2rpm azure-proxy-agent --path ../proxy_agent/Cargo.toml

%bcond check 1

Name:           azure-proxy-agent
Version:        1.0.36
Release:        %autorelease
Summary:        Microsoft Azure Guest Proxy Agent
SourceLicense:  MIT
License:        MIT
URL:            https://github.com/Azure/GuestProxyAgent
Source0:        %{name}-%{version}.tar.gz
# vendor.tar.xz for local build only
Source1:        vendor.tar.xz
Patch0:         0001-Update-Cargo-files-for-Linux-only.patch
Patch1:         0002-Fix-doc-test.patch
Patch2:         0003-Add-feature-for-linux-service-test.patch
ExclusiveArch:  x86_64 aarch64

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  clang
BuildRequires:  libbpf-devel 

%global _description %{expand:
Azure Guest Proxy Agent.}

%description %{_description}
%global _ebpf_path linux-ebpf

%prep
%autosetup -p2 -a0
# %cargo_prep
# vendor mode for local build and manual extract Source1 into vendor
mkdir vendor
tar -xf %{SOURCE1} -C vendor
%cargo_prep -v vendor

### %cargo_generate_buildrequires inspects Cargo.lock and emits BuildRequires: crate(...) lines. 
### Those are only for offline builds using system crates, not for vendored builds
# %generate_buildrequires
# %cargo_generate_buildrequires

%build
# build ebpf
ebpf_arch=x86
ebpf_arch_inc=
%ifarch aarch64
ebpf_arch=arm64
ebpf_arch_inc=aarch64-linux-gnu
%endif
clang -g -target bpf -Werror -O2 -D__TARGET_ARCH_$ebpf_arch -I/usr/include/$ebpf_arch_inc -c %{_ebpf_path}/ebpf_cgroup.c -o %{_ebpf_path}/ebpf_cgroup.o
# build rust
%cargo_vendor_manifest
%cargo_build

%install
# custome install the files for azure-proxy-agent service
mkdir -p %{buildroot}/usr/sbin/
mkdir -p %{buildroot}/etc/azure/
mkdir -p %{buildroot}/usr/lib/systemd/system/
mkdir -p %{buildroot}/usr/lib/azure-proxy-agent/
cp -f proxy_agent/config/GuestProxyAgent.linux.json %{buildroot}/etc/azure/proxy-agent.json
cp -f proxy_agent_setup/src/linux/azure-proxy-agent.service %{buildroot}/usr/lib/systemd/system/
cp -f %{_ebpf_path}/ebpf_cgroup.o %{buildroot}/usr/lib/azure-proxy-agent/
cp -f target/release/azure-proxy-agent %{buildroot}/usr/sbin/

%if %{with check}
%check
cp -f -T proxy_agent/config/GuestProxyAgent.linux.json target/release/deps/proxy-agent.json
%cargo_test
%endif

%post
%systemd_post azure-proxy-agent.service
   systemctl unmask azure-proxy-agent.service
   systemctl daemon-reload
   systemctl start azure-proxy-agent.service
   systemctl enable azure-proxy-agent.service

%files
%license LICENSE
%defattr(-,root,root,-)
/usr/lib/systemd/system/azure-proxy-agent.service
/usr/sbin/azure-proxy-agent
/etc/azure/proxy-agent.json
/usr/lib/azure-proxy-agent/ebpf_cgroup.o

%changelog
%autochangelog
