name: CD Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'

jobs:
  release:
    uses: ./.github/workflows/reusable-build.yml
    with:
      generate_release: true
    permissions:
      actions: read
      contents: write
      deployments: read
      packages: write
      pull-requests: write
      security-events: write