name: CI Build & Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: cicd-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check -l
      - name: Clippy
        run: cargo clippy -- -D warnings

  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      generate_release: false
