name: Check Spelling

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: cspell.json
          # On pull requests, only check files changed in the PR.
          incremental_files_only: ${{ github.event_name == 'pull_request' }}
          # Fail the check when spelling issues are found.
          strict: true
          inline: warning